Adding a file
antuanettaV/homework2 pull request #6
Opened 2024-06-27 21:17 UTC by antuanettaV

Please kindly check my homework (week4). Thanks in advance.

2024-06-29 08:35 UTC, vdaguenet requested changes
Unfortunately, the to-do list section of the homework was misunderstood. Please make the necessary adjustments, and I will have a second look at your solution.

2024-06-29 08:35 UTC, vdaguenet commented on text.html
> +<script src="week.js"></script>
This file is not the one where you implemented week 4's homework.

2024-06-29 08:35 UTC, vdaguenet commented on java.js
> +  } else if (command === "Add fishing to my todo") {
`Add fishing to my todo` and `Add singing in the shower to my todo` should be handled in the same case and in a way that would work with `Add whatever to my todo`, too.

2024-06-29 18:58 UTC, antuanettaV commented
Good day, Valentin. Thank you for your feedback. I have changed my homework. Could you please kindly have a look once you will have time? Thanks in advance.

2024-06-30 08:28 UTC, vdaguenet approved these changes
Good work!

2024-06-30 08:28 UTC, vdaguenet commented on java.js
> +let state = {
Nice idea!

2024-06-30 08:28 UTC, vdaguenet commented on java.js
> +  if (command.startsWith("Hello my name is ")) {
This works fine in the context of the exercise. When dealing with real user inputs, it's recommended to clean up the command like this:
```js
const cleanCommand = command.toLowerCase().trim();
if (cleanCommand.startsWith('hello my name is')) { ... }
```

Doing so allows your code to run even if the user made a typo like `Hello my Name Is Valentin`

2024-06-30 08:28 UTC, vdaguenet commented on java.js
> +    const formattedDate = today.toLocaleDateString("en-US", options);
Nice way to format a date.

2024-07-05 03:57 UTC, merged